### ISSUE TITLE
Product page

### ISSUE THREAD

**Issue by natduboiss** [natduboiss/ecommerce-pattern-library#2]
How would I divide the product cards into sections if they are in a loop right now? I understand we need to have the cards looping with Jekyll but is there a way that I can organize the list and add sections in between them?
@thomasjbradley

**Comment by thomasjbradley** [comment]
There are a bunch of different ways, but this might work well for you.

At the top of each products Markdown file, add an entry called `category` or something, like:

```md
---
name: "Double garden"
description: |
  A two piece set of our most popular boxed succulents. The Bliss and the Zebra succulent. Good price for both.
non_conflict: false
image: "/images/products/smallgarden2.jpg"
price: 45
category: "garden"
---
```

Then in the loop you’d use an `if-statement` to check that the product has the right category:

```liquid
{% for product in site.products %}
  {% if product.category == 'garden' %}
    {% include cards/product-card …
  {% endif %}
{% endfor %}
```

You’d then have multiple loops on the page, one for each category you want to display.
```

**Comment by natduboiss** [comment]
I put the category tag in each Markdown file and I also added the if-statement for the first category, but now all my images have disappeared.
@thomasjbradley

**Comment by thomasjbradley** [comment]
Please commit the recent changes so I can look at it.

**Comment by natduboiss** [comment]
Okay I've committed the changes
@thomasjbradley

**Comment by thomasjbradley** [comment]
The if-statements don’t match how the category is spelled in the MD files, for example:

```
{% if product.category == 'small-gardens' %}
```

Says `small-gardens`. But if I look inside one of the MD files, it’s spelled like this: `Small Gardens`. The if-statement and the category need to match spelling & capitalization.

**Comment by natduboiss** [comment]
Thank you!
