### ISSUE TITLE
Collab changes not being shown

### ISSUE THREAD

**Issue by natduboiss** [natduboiss/ecommerce-pattern-library#3]
Me and @migr0001 made our product page for each other in class and everything worked well. However now when we look at our website the changes aren't being shown. I can't see the changes in my code that she made. We just figured out that one of the collaborator invitation didn't go through but finally accepted it correctly but still no difference.
@thomasjbradley

**Comment by thomasjbradley** [comment]
We haven’t done that part yet—we’ll be doing it at the start of class next week. It’s expected that you cannot see your teammate’s work within your own project yet.
